---
title: "Schools_Comparison"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the libraries

```{r}
library(tidyverse)
library(readxl)
library(stringr)
library(ggplot2)
library(haven)
```
## Analysis
Data published [here](https://cepa.stanford.edu/seda/download?nid=2016&destination=node/2021#testscore) by SEDA

```{r read_dta}
df_dta <- read_dta('SEDA_geodist_long_GCS_v20.dta')
```


We only want to look at three districts so let's filter out the rest of them:
```{r}
my_districts <- c("ORLEANS PARISH","CITY OF CHICAGO SD 299","DISTRICT OF COLUMBIA PUBLIC SCHOOLS")

df_out <- df_dta %>%
    mutate(leaname_upper = str_to_upper(leaname)) %>%
    filter(leaname_upper %in% my_districts) %>%
    arrange(leaname)  
```


We won't include 2015, because it was a year of new assessments.
```{r subset_data}
df_out_subset <- df_out %>% filter(!year %in% c(2015))
df_out_subset %>% glimpse()
```

Here is a plot of the filtered data by grade and year:
```{r plot_scores}
df_out_subset %>% ggplot(aes(x = year, y = mn_all, color = leaname)) +
  geom_line()  +
  facet_grid(subject~grade) +
  theme(axis.text.x=element_text(angle=45,hjust=1)) + scale_x_continuous(breaks=c(2008,2010,2012,2014)) +
  ylab('Mean Score of All Students') + xlab('Year') + labs(color = "District") 
```


```{r save_scores_plot, echo=FALSE,results='hide'}
ggsave('comparisonofdistricts.png', plot = last_plot(), device = NULL, path = NULL,
  scale = 1, width = NA, height = NA, units = c("in", "cm", "mm"),
  dpi = 300, limitsize = TRUE)
```

If we add in error bars (standard error):
```{r}
df_out_subset%>% ggplot(aes(x = year, y = mn_all, color = leaname)) +
  geom_line()  +
  facet_grid(subject~grade) +
  theme(axis.text.x=element_text(angle=45,hjust=1)) + scale_x_continuous(breaks=c(2008,2010,2012,2014)) +
  ylab('Mean Score of All Students') + xlab('Year') + labs(color = "District") +
  geom_ribbon(aes(ymin = mn_all - mn_all_se,ymax = mn_all + mn_all_se)) 
```


```{r,echo=FALSE,results='hide'}
ggsave('comparionofdistictswitherrorbars.png', plot = last_plot(), device = NULL, path = NULL,
  scale = 1, width = NA, height = NA, units = c("in", "cm", "mm"),
  dpi = 300, limitsize = TRUE)
```
